<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE dreme[
<!ELEMENT dreme (model, motifs, run_time)>
<!ATTLIST dreme version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model 
  (command_line, positives, negatives, background, stop, norc, ngen, add_pv_thresh, 
  seed, host, when, description?)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT positives EMPTY>
<!ATTLIST positives 
  name CDATA #REQUIRED count CDATA #REQUIRED file CDATA #REQUIRED 
  last_mod_date CDATA #REQUIRED>
<!--  
  negatives must have a file and last_mod_date specified when the from
  attribute is file.
-->
<!ELEMENT negatives EMPTY>
<!ATTLIST negatives 
  name CDATA #REQUIRED count CDATA #REQUIRED from (shuffled|file) #REQUIRED
  file CDATA #IMPLIED last_mod_date CDATA #IMPLIED>
<!-- 
  background allows DNA and RNA (AA is not going to be supported with DREME) 
  however currently only DNA is implemented. Note that when type is dna the
  value for T must be supplied and when the type is rna the value for U must
  be supplied. The sum of the frequencies must be 1 (with a small error).
-->
<!ELEMENT background EMPTY>
<!ATTLIST background 
  type (dna|rna) #REQUIRED
  A CDATA #REQUIRED C CDATA #REQUIRED G CDATA #REQUIRED 
  T CDATA #IMPLIED U CDATA #IMPLIED 
  from (dataset|file) #REQUIRED 
  file CDATA #IMPLIED last_mod_date CDATA #IMPLIED>
<!ELEMENT stop EMPTY>
<!ATTLIST stop 
  evalue CDATA #IMPLIED count CDATA #IMPLIED time CDATA #IMPLIED>
<!ELEMENT norc (#PCDATA)>
<!ELEMENT ngen (#PCDATA)>
<!ELEMENT seed (#PCDATA)>
<!ELEMENT add_pv_thresh (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (pos*, match*)>
<!ATTLIST motif
  id CDATA #REQUIRED seq CDATA #REQUIRED length CDATA #REQUIRED 
  nsites CDATA #REQUIRED p CDATA #REQUIRED n CDATA #REQUIRED
  pvalue CDATA #REQUIRED evalue CDATA #REQUIRED unerased_evalue CDATA #REQUIRED>
<!--
  pos allows DNA and RNA (AA is not going to be supported with DREME)
  however current only DNA is implemented. When the type in the background
  is 'dna' pos must have a T attribute and when it is 'rna' pos must have a
  U attribute
-->
<!ELEMENT pos EMPTY>
<!ATTLIST pos
  i CDATA #REQUIRED A CDATA #REQUIRED C CDATA #REQUIRED G CDATA #REQUIRED 
  T CDATA #IMPLIED U CDATA #IMPLIED>
<!ELEMENT match EMPTY>
<!ATTLIST match
  seq CDATA #REQUIRED p CDATA #REQUIRED n CDATA #REQUIRED 
  pvalue CDATA #REQUIRED evalue CDATA #REQUIRED>
<!ELEMENT run_time EMPTY>
<!ATTLIST run_time
  cpu CDATA #REQUIRED real CDATA #REQUIRED stop (evalue|count|time) #REQUIRED>
]>
<dreme version="4.10.1" release="Wed Mar 25 11:40:43 2015 +1000">
  <model>
    <command_line>dreme -oc dreme_example_output_files -png -p Klf1.fna</command_line>
    <positives name="Klf1" count="904" file="Klf1.fna" last_mod_date="Tue Mar 17 15:38:33 PDT 2015" />
    <negatives name="shuffled positive sequences" count="904" from="shuffled"/>
    <background type="dna" A="0.255" C="0.245" G="0.243" T="0.257" from="dataset"/>
    <stop evalue="0.05"/>
    <norc>FALSE</norc>
    <ngen>100</ngen>
    <add_pv_thresh>0.01</add_pv_thresh>
    <seed>1</seed>
    <host>D-69-91-184-224.dhcp4.washington.edu</host>
    <when>Fri Aug 07 16:03:31 PDT 2015</when>
  </model>
  <motifs>
    <motif id="m01" seq="CCMCRCCC" length="8" nsites="454" p="350" n="49" pvalue="1.8e-071" evalue="7.6e-067" unerased_evalue="7.6e-067">
      <pos i="1" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.550661" C="0.449339" G="0.000000" T="0.000000"/>
      <pos i="4" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="5" A="0.733480" C="0.000000" G="0.266520" T="0.000000"/>
      <pos i="6" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="8" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <match seq="CCACACCC" p="175" n="19" pvalue="2.4e-036" evalue="1.0e-031"/>
      <match seq="CCCCACCC" p="128" n="25" pvalue="1.5e-019" evalue="6.4e-015"/>
      <match seq="CCACGCCC" p="55" n="3" pvalue="5.3e-014" evalue="2.3e-009"/>
      <match seq="CCCCGCCC" p="53" n="3" pvalue="2.0e-013" evalue="8.6e-009"/>
    </motif>
    <motif id="m02" seq="BTTATCW" length="7" nsites="613" p="449" n="190" pvalue="5.6e-038" evalue="2.4e-033" unerased_evalue="1.3e-033">
      <pos i="1" A="0.000000" C="0.484502" G="0.216966" T="0.298532"/>
      <pos i="2" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="3" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="4" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="5" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="6" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="0.415987" C="0.000000" G="0.000000" T="0.584013"/>
      <match seq="CTTATCT" p="169" n="56" pvalue="2.0e-016" evalue="8.6e-012"/>
      <match seq="CTTATCA" p="109" n="36" pvalue="1.0e-010" evalue="4.3e-006"/>
      <match seq="TTTATCT" p="106" n="42" pvalue="2.1e-008" evalue="9.0e-004"/>
      <match seq="GTTATCA" p="69" n="23" pvalue="4.5e-007" evalue="1.9e-002"/>
      <match seq="GTTATCT" p="64" n="28" pvalue="7.6e-005" evalue="3.2e+000"/>
      <match seq="TTTATCA" p="61" n="26" pvalue="7.8e-005" evalue="3.3e+000"/>
    </motif>
    <motif id="m03" seq="MCRCCCA" length="7" nsites="340" p="283" n="109" pvalue="6.9e-024" evalue="2.9e-019" unerased_evalue="2.5e-040">
      <pos i="1" A="0.458824" C="0.541176" G="0.000000" T="0.000000"/>
      <pos i="2" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.729412" C="0.000000" G="0.270588" T="0.000000"/>
      <pos i="4" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="5" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <match seq="CCACCCA" p="129" n="48" pvalue="6.2e-011" evalue="2.6e-006"/>
      <match seq="ACACCCA" p="102" n="42" pvalue="1.0e-007" evalue="4.4e-003"/>
      <match seq="ACGCCCA" p="46" n="10" pvalue="4.3e-007" evalue="1.8e-002"/>
      <match seq="CCGCCCA" p="43" n="17" pvalue="4.4e-004" evalue="1.9e+001"/>
    </motif>
    <motif id="m04" seq="RARGAAA" length="7" nsites="539" p="398" n="215" pvalue="4.8e-020" evalue="2.1e-015" unerased_evalue="2.7e-015">
      <pos i="1" A="0.543599" C="0.000000" G="0.456401" T="0.000000"/>
      <pos i="2" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.534323" C="0.000000" G="0.465677" T="0.000000"/>
      <pos i="4" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="5" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <match seq="AAAGAAA" p="149" n="68" pvalue="2.5e-009" evalue="1.1e-004"/>
      <match seq="AAGGAAA" p="130" n="57" pvalue="9.3e-009" evalue="4.0e-004"/>
      <match seq="GAAGAAA" p="122" n="54" pvalue="3.8e-008" evalue="1.6e-003"/>
      <match seq="GAGGAAA" p="110" n="67" pvalue="4.2e-004" evalue="1.8e+001"/>
    </motif>
    <motif id="m05" seq="AKAAAM" length="6" nsites="1018" p="585" n="415" pvalue="5.3e-016" evalue="2.3e-011" unerased_evalue="1.7e-015">
      <pos i="1" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="0.000000" C="0.000000" G="0.629666" T="0.370334"/>
      <pos i="3" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="4" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="5" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="0.617878" C="0.382122" G="0.000000" T="0.000000"/>
      <match seq="AGAAAA" p="302" n="208" pvalue="5.6e-007" evalue="2.4e-002"/>
      <match seq="ATAAAA" p="192" n="117" pvalue="1.7e-006" evalue="7.3e-002"/>
      <match seq="ATAAAC" p="128" n="75" pvalue="5.0e-005" evalue="2.1e+000"/>
      <match seq="AGAAAC" p="211" n="145" pvalue="5.8e-005" evalue="2.5e+000"/>
    </motif>
    <motif id="m06" seq="CTGTSTS" length="7" nsites="516" p="384" n="235" pvalue="9.1e-014" evalue="3.8e-009" unerased_evalue="1.6e-009">
      <pos i="1" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="3" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="4" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="5" A="0.000000" C="0.531008" G="0.468992" T="0.000000"/>
      <pos i="6" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="7" A="0.000000" C="0.453488" G="0.546512" T="0.000000"/>
      <match seq="CTGTGTG" p="139" n="72" pvalue="5.6e-007" evalue="2.3e-002"/>
      <match seq="CTGTCTC" p="129" n="73" pvalue="1.8e-005" evalue="7.6e-001"/>
      <match seq="CTGTCTG" p="127" n="77" pvalue="1.3e-004" evalue="5.3e+000"/>
      <match seq="CTGTGTC" p="87" n="55" pvalue="3.3e-003" evalue="1.4e+002"/>
    </motif>
    <motif id="m07" seq="AGGGCGK" length="7" nsites="105" p="96" n="28" pvalue="8.3e-011" evalue="3.5e-006" unerased_evalue="5.9e-017">
      <pos i="1" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="3" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="4" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="5" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="7" A="0.000000" C="0.000000" G="0.514286" T="0.485714"/>
      <match seq="AGGGCGT" p="50" n="10" pvalue="5.1e-008" evalue="2.1e-003"/>
      <match seq="AGGGCGG" p="48" n="18" pvalue="1.1e-004" evalue="4.6e+000"/>
    </motif>
    <motif id="m08" seq="CCTKCCY" length="7" nsites="576" p="406" n="278" pvalue="3.4e-010" evalue="1.4e-005" unerased_evalue="2.7e-008">
      <pos i="1" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="4" A="0.000000" C="0.000000" G="0.491319" T="0.508681"/>
      <pos i="5" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="0.000000" C="0.467014" G="0.000000" T="0.532986"/>
      <match seq="CCTTCCT" p="144" n="85" pvalue="1.9e-005" evalue="7.9e-001"/>
      <match seq="CCTTCCC" p="122" n="75" pvalue="2.5e-004" evalue="1.0e+001"/>
      <match seq="CCTGCCC" p="125" n="82" pvalue="9.3e-004" evalue="3.9e+001"/>
      <match seq="CCTGCCT" p="135" n="94" pvalue="2.3e-003" evalue="9.5e+001"/>
    </motif>
    <motif id="m09" seq="TTAAAAW" length="7" nsites="203" p="178" n="89" pvalue="2.1e-009" evalue="8.5e-005" unerased_evalue="3.7e-005">
      <pos i="1" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="2" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="3" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="4" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="5" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="0.605911" C="0.000000" G="0.000000" T="0.394089"/>
      <match seq="TTAAAAA" p="117" n="61" pvalue="6.1e-006" evalue="2.5e-001"/>
      <match seq="TTAAAAT" p="78" n="38" pvalue="8.0e-005" evalue="3.3e+000"/>
    </motif>
    <motif id="m10" seq="AAATAH" length="6" nsites="494" p="350" n="242" pvalue="3.9e-008" evalue="1.6e-003" unerased_evalue="8.2e-010">
      <pos i="1" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="4" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="5" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="0.354251" C="0.277328" G="0.000000" T="0.368421"/>
      <match seq="AAATAC" p="123" n="71" pvalue="4.9e-005" evalue="2.0e+000"/>
      <match seq="AAATAT" p="149" n="100" pvalue="5.1e-004" evalue="2.1e+001"/>
      <match seq="AAATAA" p="147" n="105" pvalue="2.6e-003" evalue="1.1e+002"/>
    </motif>
    <motif id="m11" seq="CATYTCC" length="7" nsites="158" p="144" n="72" pvalue="1.1e-007" evalue="4.3e-003" unerased_evalue="2.8e-004">
      <pos i="1" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="4" A="0.000000" C="0.455696" G="0.000000" T="0.544304"/>
      <pos i="5" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="6" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <match seq="CATTTCC" p="79" n="32" pvalue="2.5e-006" evalue="1.0e-001"/>
      <match seq="CATCTCC" p="70" n="42" pvalue="4.1e-003" evalue="1.7e+002"/>
    </motif>
    <motif id="m12" seq="CAGMCAC" length="7" nsites="191" p="162" n="88" pvalue="2.8e-007" evalue="1.2e-002" unerased_evalue="2.3e-005">
      <pos i="1" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="4" A="0.434555" C="0.565445" G="0.000000" T="0.000000"/>
      <pos i="5" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="6" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="7" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <match seq="CAGACAC" p="77" n="33" pvalue="9.3e-006" evalue="3.8e-001"/>
      <match seq="CAGCCAC" p="100" n="60" pvalue="5.9e-004" evalue="2.4e+001"/>
    </motif>
    <motif id="m13" seq="CACAGY" length="6" nsites="574" p="415" n="312" pvalue="4.8e-007" evalue="2.0e-002" unerased_evalue="1.2e-005">
      <pos i="1" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="4" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="5" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="6" A="0.000000" C="0.559233" G="0.000000" T="0.440767"/>
      <match seq="CACAGC" p="263" n="184" pvalue="1.0e-005" evalue="4.2e-001"/>
      <match seq="CACAGT" p="226" n="167" pvalue="4.6e-004" evalue="1.9e+001"/>
    </motif>
    <motif id="m14" seq="CTGGRGA" length="7" nsites="233" p="205" n="125" pvalue="6.9e-007" evalue="2.8e-002" unerased_evalue="2.5e-004">
      <pos i="1" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="2" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="3" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="4" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="5" A="0.463519" C="0.000000" G="0.536481" T="0.000000"/>
      <pos i="6" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="7" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <match seq="CTGGGGA" p="117" n="69" pvalue="1.3e-004" evalue="5.2e+000"/>
      <match seq="CTGGAGA" p="102" n="66" pvalue="2.2e-003" evalue="9.1e+001"/>
    </motif>
    <motif id="m15" seq="SACGTGA" length="7" nsites="44" p="43" n="9" pvalue="7.4e-007" evalue="3.0e-002" unerased_evalue="1.0e-002">
      <pos i="1" A="0.000000" C="0.590909" G="0.409091" T="0.000000"/>
      <pos i="2" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <pos i="3" A="0.000000" C="1.000000" G="0.000000" T="0.000000"/>
      <pos i="4" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="5" A="0.000000" C="0.000000" G="0.000000" T="1.000000"/>
      <pos i="6" A="0.000000" C="0.000000" G="1.000000" T="0.000000"/>
      <pos i="7" A="1.000000" C="0.000000" G="0.000000" T="0.000000"/>
      <match seq="CACGTGA" p="25" n="6" pvalue="4.0e-004" evalue="1.6e+001"/>
      <match seq="GACGTGA" p="18" n="3" pvalue="7.0e-004" evalue="2.9e+001"/>
    </motif>
  </motifs>
  <run_time cpu="381.35" real="386.60" stop="evalue"/>
</dreme>
